
[workspace]
resolver = "2"
members = ["src-tauri","migration","entity", "handle", "web", "mio", "test_cli","type-build", "candle"]

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
mio = { version = "1.0.2", features = ["os-poll","net"] }
anyhow = "1"

