[package]
name = "trpl"
version = "0.1.0"
edition = "2024"

[dependencies]
trpl = "0.2.0"
# 依赖的依赖不是项目的依赖
futures = "0.3.31"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
