//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::dept::Entity as Dept;
pub use super::menu::Entity as Menu;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
